#!/usr/bin/env bash

display_usage() {
  echo "Usage: $(basename "$0") [commit SHA]"
  echo ""
  echo "  Please set ISSUE_PATTERN and ISSUE_URL. For example:"
  echo ""
  echo "    REFERENCE_PATTERN=PS-\d\d\d\d"
  echo "    TARGET_URL=https://myorg.atlassian.net/browse"
  echo ""
  echo "Bugs and suggestions: <https://github.com/MarounMaroun/gitlink/issues>"
  exit 1
}

if [[ -z "$REFERENCE_PATTERN" ]] || [[ -z "$TARGET_URL" ]]; then
  display_usage
  exit 1
fi

sha="$1"

command=
if command -v open > /dev/null; then
  command=open
elif command -v xdg-open > /dev/null; then
  command=xdg-open
elif command -v gnome-open > /dev/null; then
  command=gnome-open
fi

reference_ids=($(git show -s --format=%s "$sha" | grep -o --color=never "$REFERENCE_PATTERN"))
if [[ ${#reference_ids[@]} == 2 ]]; then
  for reference_id in "${reference_ids[@]}"; do
    echo "$TARGET_URL/$reference_id"
  done
  exit
fi

if [[ -n "$reference_ids" ]]; then
  "$command" "$TARGET_URL/$reference_ids"
fi

